package com.redhat.slapolicy_example;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class SLAEscalation implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "waitingTimeBeforeEscalate")
	private java.lang.String waitingTimeBeforeEscalate;
	@org.kie.api.definition.type.Label(value = "groups")
	private java.lang.String groups;

	public SLAEscalation() {
	}

	public java.lang.String getWaitingTimeBeforeEscalate() {
		return this.waitingTimeBeforeEscalate;
	}

	public void setWaitingTimeBeforeEscalate(
			java.lang.String waitingTimeBeforeEscalate) {
		this.waitingTimeBeforeEscalate = waitingTimeBeforeEscalate;
	}

	public java.lang.String getGroups() {
		return this.groups;
	}

	public void setGroups(java.lang.String groups) {
		this.groups = groups;
	}

	public SLAEscalation(java.lang.String waitingTimeBeforeEscalate,
			java.lang.String groups) {
		this.waitingTimeBeforeEscalate = waitingTimeBeforeEscalate;
		this.groups = groups;
	}

}